import { Sorter } from "./Sorter";
import { NumberCollection } from "./NumberCollection";
import { CharacterCollection } from "./CharacterCollection";
import { LinkedList } from "./LinkedListCollection";

const numberCollection = new NumberCollection([10, 3, -5, 0]);
const numberSorter = new Sorter(numberCollection);
numberSorter.sort();
const characterCollection = new CharacterCollection("HelloThisIsPodo");
const stringSorter = new Sorter(characterCollection);
stringSorter.sort();
const linkedList = new LinkedList();
linkedList.add(500);
linkedList.add(50);
linkedList.add(-500);
linkedList.add(530);
linkedList.add(520);
const listSorter = new Sorter(linkedList);
listSorter.sort();
console.log(numberCollection.data);
console.log(characterCollection.data);
console.log(linkedList.print());
